more safeguards in the analyzer Makefile

diff --git a/analyzer/Makefile b/analyzer/Makefile
--- a/analyzer/Makefile
+++ b/analyzer/Makefile
@@ -1,14 +1,6 @@
 CXX = g++
 CXXFLAGS = -O3 -msse2 -mssse3 -mfpmath=sse -funroll-loops -ffast-math
 CXXFLAGS += $(shell root-config --cflags)
-# CXXFLAGS += -I$(DOGS_PATH)/DCBase
-# CXXFLAGS += -I$(DOGS_PATH)/DCDB
-# CXXFLAGS += -I$(DOGS_PATH)/DCGeo
-# CXXFLAGS += -I$(DOGS_PATH)/DCEvent
-# CXXFLAGS += -I$(DOGS_PATH)/DCValidity
-# CXXFLAGS += -I$(DOGS_PATH)/DCRegistry
-# CXXFLAGS += -I$(DOGS_PATH)/DCDBInterface
-# CXXFLAGS += -I$(DOGS_PATH)/DCCalibApply
 
 # OBJDIR = ./objects
 ODIR = ./objects
@@ -19,34 +11,7 @@ CXXFLAGS  += -I$(RATPAC_PATH)/include/
 
 LIBS += $(shell root-config --libs) -lGeom -lGui -lSpectrum 
 LIBS += -L$(RATPAC_PATH)/lib -lRATEvent
-# LIBS += -L$(DOGS_PATH)/lib
-# LIBS += -lDCBase
-# LIBS += -lDCDB
-# LIBS += -lDCGeo
-# LIBS += -lDCEvent
-# LIBS += -lDCValidity
-# LIBS += -lDCRegistry
-# LIBS += -lDCDBInterface
-# LIBS += -lDCCalibApply
-# LIBS += -lDCUtil
 
-# all: analyzer.exe 
-# 
-# $(OBJDIR)/%.o:$(SRCDIR)/%.cc
-# 	@mkdir -p $(OBJDIR)
-# 	$(CXX) $(CXXFLAGS) -c -o $@ $<
-# 
-# $(OBJDIR)/%.o:$(INCDIR)/%.cc
-# 	@mkdir -p $(OBJDIR)
-# 	$(CXX) $(CXXFLAGS) -c -o $@ $<
-# 
-# $(OBJDIR)/%.o:$(SRCDIR)/%.C
-# 	@mkdir -p $(OBJDIR)
-# 	$(CXX) $(CXXFLAGS) -c -o $@ $<
-# 
-# analyzer.exe: $(OBJDIR)/ProgressBar.o $(OBJDIR)/analyzer.o $(OBJDIR)/main.o 
-# 	$(CXX) $(CXXFLAGS) -o analyzer.exe $^ $(LIBS) 	
-# 	strip analyzer.exe
 	
 all: RATPAC_analyzer.exe
 
@@ -60,12 +25,29 @@ $(ODIR)/main.o:main.cc
 $(ODIR)/%.o:%.cc %.hh
 	$(CXX) -c $< -o $@ $(CXXFLAGS) 
 	 
-RATPAC_analyzer.exe: $(OBJS)
-	$(CXX) $(OBJS) $(CXXFLAGS) $(LIBS) -o $@
-	
-# data_mc_plot_2ang_FinalFitTree.exe: $(OBJDIR)/ProgressBar.o $(OBJDIR)/data_mc_plot_2ang_FinalFitTree.o $(OBJDIR)/main.o
-# 	$(CXX) $(CXXFLAGS) -o data_mc_plot_2ang_FinalFitTree.exe $^ $(LIBS) 	
-# 	strip data_mc_plot_2ang_FinalFitTree.exe	
+RATPAC_analyzer.exe: check_min $(OBJS) 
+	$(CXX) $(OBJS) $(CXXFLAGS) $(LIBS) -o $@	
 	
 clean:
 	@rm -f *.exe $(ODIR)/*.o *~ include/*~
+	
+.PHONY: check_min
+check_min::
+	@echo "Testing framework configuration:";
+	@if test ! -e $$SHELL; \
+	then \
+		echo " Makefile needs bash and file /bin/bash is missing. Install bash or set proper link."; \
+		exit 254; \
+	fi;
+	@if [ x$(ROOTSYS) = x ] || ! hash root-config 2>&- ; \
+	then \
+		echo " ROOTSYS not defined or root-config not found. Install or set properly ROOT before installing RAT-PAC framework."; \
+		exit 253; \
+	else \
+		echo " Your ROOT version is: "$(shell root-config --version); \
+	fi;
+	@if [ x$(RATPAC_PATH) = x ]; \
+	then \
+		echo " RATPAC_PATH is not defined. Set RATPAC_PATH to your rat-pac directory."; \
+		exit 252; \
+	fi;	
